FROM ghcr.io/libertech-fr/sesame-orchestrator

USER root

RUN apk add --no-cache chromium
RUN yarn install --frozen-lockfile --production=false --non-interactive

ENV NODE_ENV=development
ENV PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH=/usr/bin/chromium

WORKDIR /data
