export enum ActionType {
  LIST_BACKENDS = 'LIST_BACKENDS',
  PING_TARGET = 'PING_TARGET',
  IDENTITY_CREATE = 'IDENTITY_CREATE',
  IDENTITY_UPDATE = 'IDENTITY_UPDATE',
  IDENTITY_DELETE = 'IDENTITY_DELETE',
  IDENTITY_PASSWORD_RESET = 'IDENTITY_PASSWORD_RESET',
  IDENTITY_PASSWORD_CHANGE = 'IDENTITY_PASSWORD_CHANGE',
}
