version: '3'
services:
  so:
    build: . 
    container_name: so
    environment: 
      - NODE_ENV=development
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - API_KEY=abcdef
    volumes:
      - "..:/data"
    ports: 
      - "3002:3000"
      - "9229:9229"
    networks:
      - dev
  redis:
    image: redis
    restart: always
    networks:
      - dev
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
networks:
  dev: 
    external: true      
