type: Group
label: Identité
elements:
  - type: HorizontalLayout
    elements:
      - type: Control
        label: UID
        scope: "#/properties/uid"
        options:
          required: true
      - type: Control
        label: Nom
        scope: "#/properties/sn"
        options:
          required: true
          readOnly: true
      - type: Control
        label: Prénom
        scope: "#/properties/givenName"
        options:
          required: true
          readOnly: true
  - type: HorizontalLayout
    elements:
      - type: Control
        label: Adresse postale
        scope: "#/properties/postalAddress"
        options:
          readOnly: true
  - type: HorizontalLayout
    elements:
      - type: Control
        label: Email
        scope: "#/properties/mail"
        options:
          format: email
      - type: Control
        label: Mobile
        scope: "#/properties/mobile"
      - type: Control
        label: Téléphone
        scope: "#/properties/telephoneNumber"
        options:
          readOnly: true
  - type: HorizontalLayout
    elements:
      - type: Control
        label: Titre
        scope: "#/properties/title"
        options:
          format: email
      - type: Control
        label: Type de population
        scope: "#/properties/departmentNumber"
        options:
          required: false
          readOnly: true
          suggestion:
            - "adm"
            - "etd"
            - "esn"
  - type: HorizontalLayout
    elements:
      - type: Control
        label: Photo
        scope: "#/properties/jpegPhoto"
        options:
          format: file
          storage: picture
