import type { MenuItem } from '~/constants/types'
import { useIdentityStates } from '~/composables/useIdentityStates'
import { MenuPart } from '~/constants/variables'
import { IdentityState } from '~/constants/enums'

export function getDefaultMenuEntries(): MenuItem[] {
  const { getStateBadge } = useIdentityStates()

  function normalizeNameFromLabel(label: string): string {
    return label.toLowerCase().trim().replace(/\s+/g, '_')
  }

  return [
    {
      icon: 'mdi-account',
      label: 'Liste des identités',
      name: 'liste_des_identités',
      path: '/identities/table?sort[metadata.lastUpdatedAt]=desc&skip=0',
      color: 'primary',
      badge: { color: 'primary' },
      part: normalizeNameFromLabel(MenuPart.DONNEES),
      hideInMenuBar: false,
      acl: ['/management/identities'],
    },
    {
      icon: 'mdi-download-outline',
      label: 'Exporter',
      name: 'exporter',
      path: '/identities/export',
      color: 'accent',
      part: normalizeNameFromLabel(MenuPart.DONNEES),
      hideInMenuBar: true,
      acl: ['/management/identities'],
    },
    {
      icon: 'mdi-book-clock',
      label: 'Journal des jobs',
      name: 'journal_des_jobs',
      path: '/jobs/table?filters[:state]=-1',
      color: 'info',
      part: normalizeNameFromLabel(MenuPart.DONNEES),
      hideInMenuBar: false,
      acl: ['/core/jobs'],
    },
    {
      icon: 'mdi-timeline-clock-outline',
      label: 'Cycle de vie des identités',
      name: 'cycle_de_vie_des_identités',
      path: '/lifecycles/table',
      color: 'info',
      part: normalizeNameFromLabel(MenuPart.DONNEES),
      hideInMenuBar: false,
      acl: ['/management/lifecycle'],
    },
    {
      icon: 'mdi-clipboard-text-clock',
      label: 'Historique des changements',
      name: 'historique_des_changements',
      path: '/audits/table',
      color: 'lime-8',
      hideInMenuBar: false,
      part: normalizeNameFromLabel(MenuPart.DONNEES),
      acl: ['/core/audits'],
    },
    {
      icon: 'mdi-set-merge',
      label: 'Detection des doublons',
      name: 'detection_des_doublons',
      path: '/identities/fusion',
      color: 'positive',
      part: normalizeNameFromLabel(MenuPart.DONNEES),
      hideInMenuBar: true,
      acl: ['/management/identities'],
    },
    {
      icon: 'mdi-trash-can',
      label: 'Corbeille',
      name: 'corbeille',
      path: '/identities/trash',
      color: 'grey-10',
      hideInMenuBar: true,
      part: normalizeNameFromLabel(MenuPart.DONNEES),
      acl: ['/management/identities'],
    },
    {
      icon: 'mdi-account-check',
      label: 'A valider',
      name: 'a_valider',
      path: `/identities/table?sort[metadata.lastUpdatedAt]=desc&skip=0&filters[#state]=${IdentityState.TO_VALIDATE}`,
      color: 'warning',
      textColor: 'black',
      badge: getStateBadge(IdentityState.TO_VALIDATE),
      part: normalizeNameFromLabel(MenuPart.ETATS),
      hideInMenuBar: false,
      acl: ['/management/identities'],
    },
    {
      icon: 'mdi-account-alert',
      label: 'A compléter',
      name: 'a_compléter',
      path: `/identities/table?sort[metadata.lastUpdatedAt]=desc&skip=0&filters[%23state]=${IdentityState.TO_COMPLETE}`,
      color: 'secondary',
      textColor: 'black',
      badge: getStateBadge(IdentityState.TO_COMPLETE),
      part: normalizeNameFromLabel(MenuPart.ETATS),
      hideInMenuBar: false,
      acl: ['/management/identities'],
    },
    {
      icon: 'mdi-sync',
      label: 'A synchroniser',
      name: 'a_synchroniser',
      path: `/identities/table?readonly=1&sort[metadata.lastUpdatedAt]=desc&skip=0&filters[%23state]=${IdentityState.TO_SYNC}`,
      color: 'orange-8',
      badge: getStateBadge(IdentityState.TO_SYNC),
      part: normalizeNameFromLabel(MenuPart.ETATS),
      hideInMenuBar: false,
      acl: ['/management/identities'],
    },
    {
      icon: 'mdi-loading',
      label: 'En cours de synchro.',
      name: 'en_cours_de_synchro.',
      path: `/identities/table?readonly=1&sort[metadata.lastUpdatedAt]=desc&skip=0&filters[%23state]=${IdentityState.PROCESSING}`,
      color: 'grey-8',
      badge: getStateBadge(IdentityState.PROCESSING),
      part: normalizeNameFromLabel(MenuPart.ETATS),
      hideInMenuBar: false,
      acl: ['/management/identities'],
    },
    {
      icon: 'mdi-check',
      label: 'Synchronisées',
      name: 'synchronisées',
      path: `/identities/table?sort[metadata.lastUpdatedAt]=desc&skip=0&filters[%23state]=${IdentityState.SYNCED}`,
      badge: getStateBadge(IdentityState.SYNCED),
      color: 'positive',
      part: normalizeNameFromLabel(MenuPart.ETATS),
      hideInMenuBar: false,
      acl: ['/management/identities'],
    },
    {
      icon: 'mdi-account-switch-outline',
      label: 'Fusionnées',
      name: 'fusionnées',
      path: '/identities/table?sort[metadata.lastUpdatedAt]=desc&skip=0&filters[~primaryEmployeeNumber]=true',
      color: 'linear-gradient(135deg, #7C3AED 0%, #EC4899 50%, #F97316 100%)',
      textColor: 'white',
      badge: {
        color: 'linear-gradient(135deg, #7C3AED 0%, #EC4899 50%, #F97316 100%)',
        textColor: 'white',
      },
      part: normalizeNameFromLabel(MenuPart.ETATS),
      hideInMenuBar: false,
      acl: ['/management/identities'],
    },
    {
      icon: 'mdi-account-remove',
      label: 'En erreur',
      name: 'en_erreur',
      path: `/identities/table?sort[metadata.lastUpdatedAt]=desc&skip=0&filters[%23state]=${IdentityState.ON_ERROR}`,
      color: 'negative',
      badge: getStateBadge(IdentityState.ON_ERROR),
      part: normalizeNameFromLabel(MenuPart.ETATS),
      hideInMenuBar: false,
      acl: ['/management/identities'],
    },
    {
      icon: 'mdi-publish-off',
      label: 'À ne pas synchroniser',
      name: 'à_ne_pas_synchroniser',
      path: `/identities/table?sort[metadata.lastUpdatedAt]=desc&skip=0&filters[%23state]=${IdentityState.DONT_SYNC}`,
      color: 'black',
      badge: getStateBadge(IdentityState.DONT_SYNC),
      part: normalizeNameFromLabel(MenuPart.ETATS),
      hideInMenuBar: false,
      acl: ['/management/identities'],
    },
    {
      icon: 'mdi-email-alert',
      label: 'Invitations non envoyées',
      name: 'invitations_non_envoyées',
      path: '/identities/table?limit=10&skip=0&filters[%23initState]=0&sort[metadata.lastUpdatedAt]=desc',
      color: 'negative',
      part: normalizeNameFromLabel(MenuPart.ACTIVATION),
      badge: { color: 'negative' },
      hideInMenuBar: false,
      acl: ['/management/identities'],
    },
    {
      icon: 'mdi-email-fast',
      label: 'Invitations envoyées',
      name: 'invitations_envoyées',
      path: '/identities/table?limit=10&skip=0&filters[%23initState]=1&sort[metadata.lastUpdatedAt]=desc',
      color: 'warning',
      textColor: 'black',
      part: normalizeNameFromLabel(MenuPart.ACTIVATION),
      badge: { color: 'warning', textColor: 'black' },
      hideInMenuBar: false,
      acl: ['/management/identities'],
    },
    {
      icon: 'mdi-email-open',
      label: 'Comptes activés',
      name: 'comptes_activés',
      path: '/identities/table?limit=10&skip=0&filters[%23initState]=2&sort[metadata.lastUpdatedAt]=desc',
      color: 'positive',
      textColor: 'white',
      part: normalizeNameFromLabel(MenuPart.ACTIVATION),
      badge: { color: 'positive' },
      hideInMenuBar: false,
      acl: ['/management/identities'],
    },
    {
      icon: 'mdi-email-remove',
      label: 'Invitations périmées',
      name: 'invitations_périmées',
      path: '/identities/outdated',
      color: 'accent',
      part: normalizeNameFromLabel(MenuPart.ACTIVATION),
      hideInMenuBar: false,
      acl: ['/management/identities'],
    },
  ]
}

