name: Lint

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  lint-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install app dependencies
        run: yarn install

      - name: Lint /app
        run: yarn lint
